import os
import sys
import shutil
import argparse
import subprocess
from overlap_engine import check_overlaps

VAULT_DIR = r"C:\Users\kamil\PROJECTS\uftanma"
GLOBAL_SKILLS_DIR = r"C:\Users\kamil\.gemini\antigravity\skills"

SKILL_TEMPLATE = """---
name: "{name}"
description: "{description}"
last_updated: "{date}"
id: "UFTM-SKILL-{num}"
---

# Skill: {title_name}

{description}

---

## 🚀 Quickstart

Run this skill from the CLI using `uv run` or python:
```bash
python {script_name} [subcommand]
```

---

## 📖 Operational Instructions

1. **Step 1:** Parse inputs and verify environment parameters.
2. **Step 2:** Execute core logical transformation steps.
3. **Step 3:** Validate outputs against expectations.

---

## 🛠️ Commands & Subcommands

### 1. `run`
Executes the primary workflow sequence.
*   **Arguments:**
    *   `--input` (Path, Required): The target file or directory path.

### 2. `verify`
Validates that outputs generated by this skill match system targets.
"""

SCRIPT_TEMPLATE = """import os
import sys
import argparse

def main():
    parser = argparse.ArgumentParser(description="{description}")
    parser.add_argument("--input", required=True, help="Input path")
    args = parser.parse_args()
    
    print(f"Executing workflow on: {{args.input}}")
    # TODO: Implement step execution
    print("Workflow completed successfully.")

if __name__ == "__main__":
    main()
"""

def cmd_distill(args):
    print(f"Distilling log: {args.input_log} ...")
    
    if not os.path.exists(args.input_log):
        print(f"Error: input log {args.input_log} does not exist.")
        sys.exit(1)
        
    with open(args.input_log, "r", encoding="utf-8") as f:
        log_content = f.read()

    # Extract keywords for overlap search
    keywords = ["rag", "cli", "git", "database"]
    # Look for specific tools mentioned in the log text
    for word in ["chroma", "neon", "postgres", "github", "obsidian", "jules", "archivist"]:
        if word in log_content.lower():
            keywords.append(word)
            
    print(f"Checking for inventory overlaps with name '{args.skill_name}' and keywords {keywords}...")
    overlaps = check_overlaps(args.skill_name, keywords)
    
    if overlaps:
        print("\n[WARNING] Tool Overlaps Detected in Inventories:")
        for o in overlaps:
            print(f"  - {o['name']} ({o['source']}) | Status: {o['status']}")
            print(f"    Desc: {o['description'][:80]}...")
        print("\nRecommend reviewing these tools to avoid duplicating system configurations.\n")
    else:
        print("No inventory overlaps detected. Proceeding...")

    # Establish output directory
    out_dir = args.output_dir or os.path.join(VAULT_DIR, "Skills", args.skill_name)
    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(os.path.join(out_dir, "scripts"), exist_ok=True)

    # Render files
    clean_name = args.skill_name.lower().replace(" ", "-")
    title_name = args.skill_name.replace("-", " ").title()
    script_file_name = f"scripts/{clean_name.replace('-', '_')}.py"
    
    import datetime
    today = datetime.datetime.now().strftime("%Y-%m-%d")
    
    # Assign a dummy number for the ID
    import random
    num = f"{random.randint(100, 999)}"

    rendered_skill = SKILL_TEMPLATE.format(
        name=clean_name,
        description=args.desc,
        date=today,
        num=num,
        title_name=title_name,
        script_name=script_file_name
    )
    
    rendered_script = SCRIPT_TEMPLATE.format(
        description=args.desc
    )

    with open(os.path.join(out_dir, "SKILL.md"), "w", encoding="utf-8") as f:
        f.write(rendered_skill)
        
    with open(os.path.join(out_dir, script_file_name), "w", encoding="utf-8") as f:
        f.write(rendered_script)

    print(f"Successfully distilled skill '{clean_name}' at: {out_dir}")

def cmd_validate(args):
    print(f"Validating skill configuration in: {args.skill_dir}")
    skill_md = os.path.join(args.skill_dir, "SKILL.md")
    if not os.path.exists(skill_md):
        print(f"Validation FAILED: SKILL.md missing in {args.skill_dir}")
        sys.exit(1)
        
    print("Reading and verifying SKILL.md metadata...")
    with open(skill_md, "r", encoding="utf-8") as f:
        text = f.read()
    if not text.startswith("---"):
        print("Validation FAILED: Frontmatter missing in SKILL.md")
        sys.exit(1)
        
    print("Skill verification PASSED.")

def cmd_deploy(args):
    print(f"Deploying skill to global .gemini directory...")
    if not os.path.exists(args.skill_dir):
        print(f"Error: local skill directory {args.skill_dir} does not exist.")
        sys.exit(1)
        
    skill_name = os.path.basename(args.skill_dir)
    target_dir = os.path.join(GLOBAL_SKILLS_DIR, skill_name)
    
    # Try directory symlink (requires elevated permissions on Windows sometimes)
    # If symlink fails, copy directory recursively
    try:
        if os.path.exists(target_dir):
            if os.path.islink(target_dir):
                os.unlink(target_dir)
            else:
                shutil.rmtree(target_dir)
                
        os.symlink(args.skill_dir, target_dir, target_is_directory=True)
        print(f"Successfully created symlink at: {target_dir}")
    except Exception as e:
        print(f"Symlink creation failed ({e}). Falling back to directory copy...")
        try:
            shutil.copytree(args.skill_dir, target_dir, dirs_exist_ok=True)
            print(f"Successfully copied folder to: {target_dir}")
        except Exception as copy_err:
            print(f"Deployment failed completely: {copy_err}")
            sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="workflow-distiller skill executor.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # distill
    p_dist = subparsers.add_parser("distill")
    p_dist.add_argument("--input-log", required=True, help="Path to input session log/transcript")
    p_dist.add_argument("--skill-name", required=True, help="Target skill name")
    p_dist.add_argument("--desc", required=True, help="Skill description")
    p_dist.add_argument("--output-dir", help="Optional output path")

    # validate
    p_val = subparsers.add_parser("validate")
    p_val.add_argument("--skill-dir", required=True, help="Generated skill folder path")

    # deploy
    p_dep = subparsers.add_parser("deploy")
    p_dep.add_argument("--skill-dir", required=True, help="Generated skill folder path")

    args = parser.parse_args()

    if args.command == "distill":
        cmd_distill(args)
    elif args.command == "validate":
        cmd_validate(args)
    elif args.command == "deploy":
        cmd_deploy(args)

if __name__ == "__main__":
    main()
